=== UmarKinoo/petstudio/pet-studio-elementor-widgets/schemas/testimonials.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://thepetstudio.local/schemas/testimonials.json",
  "title": "Pet Studio widget: testimonials",
  "description": "API payload shape \u2014 maps 1:1 to Elementor widget settings after normalization.",
  "type": "object",
  "properties": {
    "reviews": {
      "type": "array",
      "items": {
        "$ref": "_common.json#/$defs/review_item"
      }
    },
    "autoplay": {
      "type": "boolean"
    },
    "interval_ms": {
      "type": "integer"
    },
    "slides_desktop": {
      "type": "integer"
    },
    "slides_tablet": {
      "type": "integer"
    },
    "slides_mobile": {
      "type": "integer"
    },
    "show_dots": {
      "type": "boolean"
    }
  }
}

=== UmarKinoo/petstudio/pet-studio-elementor-widgets/fixtures/widgets/testimonials.json
{
  "reviews": [
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Not much she doesn't know",
      "quote": "There is not much she doesn't know about her profession and no dog she cannot groom. She has a wealth of experience that she is happy to pass and is still there if I need her a year on.",
      "author": "Anonymous"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Nobody else who can come as close",
      "quote": "Liza grooms dogs that nobody else dare try. She and her team are miracle workers. If Liza didn't exist, our dog wouldn't exist...it's that simple. There is nobody else who can groom or even come as close to our dog as Liza.",
      "author": "Donna"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Incredible teeth cleaning",
      "quote": "I recommend booking Skye for ultra sonic teeth cleaning. The after pics showing how much plaque she removed were incredible. No need to go to the vet and have your dog sedated. I\u2019m going make sure I stick to 3 monthly sessions. Thank you Skye",
      "author": "Karen"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Happy and relaxed",
      "quote": "My two WHWTs went in looking like sheep and came out looking completely transformed! Both dogs were happy and relaxed and not phased by their much overdue trim. A great trim.",
      "author": "Daveena"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Such a positive experience",
      "quote": "Apart from meeting so many great dogs, the thing I liked most about the course was Liza and the great group of us girls working together towards a new career. There were ups and downs, tears and laughter and overall such a positive experience.",
      "author": "Anonymous"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Totally recommend it",
      "quote": "Since finishing I have set up a small business on my own. And while it is small, it's growing and I meet lovely dogs and people. I'm much happier than before I completed the course and totally recommend it. 5 \ud83c\udf1f",
      "author": "Anonymous"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "I cannot believe the results",
      "quote": "I was mortified when I realised how bad my lurchers teeth had got. I sent a photo to Sky at The Pet Studio and she said she would be able to help using ultrasonic teeth cleaning. I cannot believe the results! I\u2019m so pleased that he didn\u2019t have to go to the vets and have an anaesthetic! And the cost was extremely reasonable. So a massive thank you to the team and a special thank you to Sky. Look forward to seeing you on our next visit!",
      "author": "Vicky"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "The girls make a BIG fuss of her!",
      "quote": "We have taken our bearded collie to The Pet Studio for many years and she is always very well groomed. The girls make a BIG fuss of her as she is now almost 15!",
      "author": "Maggie"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Taught me way more than I thought",
      "quote": "I have just completed the level 2 dog grooming assistant course and I have had an amazing time. Liza is an amazing teacher and has taught me way more than I thought I could have learned in the past 5 weeks. Definitely worth doing especially if you love animals! Thank you Liza.",
      "author": "Charlotte"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Thoroughly enjoyed the experience",
      "quote": "I recently had a day of learning to groom my own pooch! Always wanted to do it myself as she cry\u2019s like a baby every time I leave her at local groomers, but I have never had the confidence. I finally took \u2018the plunge\u2019 and I thoroughly enjoyed the whole experience and all the useful information that Liza taught us. Liza has such a natural ability and skill with dogs (and people) that she gave us all the confidence we needed.",
      "author": "Sue"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Wouldn\u2019t send my girls anywhere else",
      "quote": "Skye is fabulous with my two working cockers Maggie and Mavis. They look beautiful after their visits to the Pet Studio. I first started using Pet Studio regularly in 2011 when Lisa was my preferred groomer for our first working cocker Indie. How lovely is it that 13 years later we are still taking our dogs there and Lisa\u2019s daughter is now our regular groomer. Us owners love continuity too. I wouldn\u2019t send my girls anywhere else \ud83d\ude00",
      "author": "Sarah"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Always gave clear instructions",
      "quote": "Our Poochon, Chloe and us had a nice time doing a 1 day groom your dog course. Liza was really helpful and encouraging and always gave clear instructions. She was really patient to Chloe. We would really highly recommend.",
      "author": "Saan"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "Huge amount of experience",
      "quote": "I completed the City and Guilds 6 week course and it has provided me with all the knowledge I needed to become a dog groomer. Liza has a huge amount of experience and adapts her teaching style to each individual student. She makes sure you have the knowledge, skill and confidence to become a groomer as soon as you finish the course. She is even there to support you once you\u2019ve finished which is very reassuring! Would definitely recommend Liza and her team to anyone wanting to become a dog groomer!",
      "author": "Lauren"
    },
    {
      "icon": {
        "id": 0,
        "url": "https://thepetstudio.local/wp-content/uploads/pet-studio/media/icons/testimonial-paw.png"
      },
      "title": "A Doggy Goddess!!!",
      "quote": "She is the bravest, hardest working groomer/trainer I've ever had the pleasure of meeting and I am so honoured that she agreed to help us and has been grooming our dog over the past year. I really don't know what we wouldve done without her support! A doggy goddess!!!",
      "author": "Donna"
    }
  ],
  "autoplay": true,
  "interval_ms": 7000,
  "slides_desktop": 3,
  "slides_tablet": 2,
  "slides_mobile": 1,
  "show_dots": true
}
